// app/booking-confirmation/page.tsx
'use client';
import React, { useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'https://stayguwahati-backend.onrender.com';
export default function BookingConfirmationPage(){
 const router=useRouter(); const params=useSearchParams(); const id=params.get('id')||''; const [booking,setBooking]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{ if(!id){setLoading(false);return;} fetch(`${BACKEND_URL}/api/bookings/${id}`).then(r=>r.json()).then(d=>setBooking(d.data||d.booking||null)).catch(()=>{}).finally(()=>setLoading(false)); },[id]);
 if(loading) return <main className="min-h-screen grid place-items-center text-slate-500">Loading confirmation…</main>;
 return <main className="min-h-screen bg-slate-50 grid place-items-center p-5"><div className="w-full max-w-xl rounded-3xl bg-white p-7 text-center shadow-sm ring-1 ring-slate-200 sm:p-10"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-teal-50 text-3xl">✓</div><p className="mt-5 text-xs font-black uppercase tracking-widest text-teal-600">Booking request submitted</p><h1 className="mt-2 text-3xl font-black text-slate-950">Your request is with the host</h1><p className="mt-3 text-sm leading-6 text-slate-500">Your stay is <strong>not confirmed yet</strong>. The host will accept or reject your request, and StayGuwahati will notify you of the decision.</p>{booking&&<div className="mt-7 rounded-2xl bg-slate-50 p-5 text-left text-sm space-y-3"><div className="flex justify-between gap-4"><span className="text-slate-500">Property</span><b>{booking.propertyName}</b></div><div className="flex justify-between gap-4"><span className="text-slate-500">Dates</span><b>{booking.dates}</b></div><div className="flex justify-between gap-4"><span className="text-slate-500">Guests</span><b>{booking.guests||1}</b></div><div className="flex justify-between gap-4"><span className="text-slate-500">Total</span><b>₹{Number(booking.totalPrice||0).toLocaleString('en-IN')}</b></div><div className="flex justify-between gap-4"><span className="text-slate-500">Status</span><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-black text-amber-700">Requested</span></div></div>}<div className="mt-7 flex flex-col gap-3 sm:flex-row"><button onClick={()=>router.push('/dashboard')} className="flex-1 rounded-xl bg-teal-600 px-5 py-3 font-black text-white hover:bg-teal-700">View My Bookings</button><button onClick={()=>router.push('/')} className="flex-1 rounded-xl border border-slate-200 px-5 py-3 font-black text-slate-700">Back to Home</button></div><p className="mt-5 text-xs text-slate-400">No online payment has been taken.</p></div></main>;
}
